jaffle_shop:
  outputs:
    dev:
      dbname: <db-name>
      host: <db-host>
      pass: <db-pass>
      port: <db-port>
      schema: <db-schema-name>
      threads: 1
      type: postgres
      user: <db-user-name>
  target: dev
